version: '3.8'

services:
  nextjs:
    image: mjkundta/frontend:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    command: ["npm", "run", "start"]