GET http://localhost:3000/api/family/detail?id_family=2
Content-Type: application/json
Authorization: "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJhbmhoYW90b2FuMjAwMkBnbWFpbC5jb20iLCJpZF91c2VyIjoiMTM0ZTBhMTktMjBkNi00M2RiLWJkNjktODE1MjVjMTJhYTA3IiwicGhvbmUiOiIwOTcxMzA4NjIzIiwiaXNhZG1pbiI6ZmFsc2UsImlhdCI6MTcxMDEzMjUwNiwiZXhwIjoxNzEwMjE4OTA2fQ.AplFmAa3ScHWO9RpGbyIR3hXWB1u75Jz_podyWzULQw"