const TEXTS = {
  LOGIN_WELCOME: 'Welcome back!',
  LOGIN_TITLE: 'Please type your credentials to login',
  EMAIL: 'Email address',
  EMAIL_PLACEHOLDER: 'Enter your email address',
  PASSWORD: 'Password',
  PASSWORD_PLACEHOLDER: 'Enter your password',
  REMEMBER_ME: 'Remember me',
  FORGOT_PASSWORD: 'Forgot your password?',
  LOGIN: 'Login',
  LOGIN_OR: 'Or login with',
  LOGIN_WITH_GOOGLE: 'Login with Google',
  DONT_HAVE_ACCOUNT: "Don't have an account?",
  SIGNUP: 'Sign up',
  SIGNUP_WELCOME: 'Create an account!',
  SIGNUP_TITLE: 'Please type your credentials to sign up',
  TERMS_AND_CONDITIONS: 'I agree to the terms and conditions',
  HAVE_ACCOUNT: 'Already have an account?',
  PHONE_NUMBER: 'Phone number',
  PHONE_NUMBER_PLACEHOLDER: 'Enter your phone number',
  FIRST_NAME: 'First name',
  FIRST_NAME_PLACEHOLDER: 'Enter your first name',
  LAST_NAME: 'Last name',
  LAST_NAME_PLACEHOLDER: 'Enter your last name',
  INVALID_EMAIL: 'Invalid email address',
  INVALID_PASSWORD: 'Password must be at least 6 characters long',
  EMAIL_REQUIRED: 'Email address is required',
  PASSWORD_REQUIRED: 'Password is required',
  FIRST_NAME_REQUIRED: 'First name is required',
  LAST_NAME_REQUIRED: 'Last name is required',
  PHONE_NUMBER_REQUIRED: 'Phone number is required',
  TERMS_AND_CONDITIONS_REQUIRED: 'You must agree to the terms and conditions',
  INVALID_PHONE_NUMBER: 'Invalid phone number',
};

export default TEXTS;
